### PR TITLE
Fix typo on string 31

### PR DESCRIPTION
**Pull request by kant**

### CODE REVIEW

**Comment by mmcguill** [comment]
Thank you for this PR, I appreciate it. Unfortunately for complicated licensing reasons I don't accept any pull requests or external contributions, but I will fix this typo for you in the next release. All the best,-Mark

**Comment by marcelstoer** [comment]
> for complicated licensing reasons I don't accept any pull requests

Care to elaborate? Could you document this publicly in e.g. the README?

**Comment by Ben-Voris** [comment]
Please do document this. For ideas of how to do this: https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

**Comment by mmcguill** [comment]
> > for complicated licensing reasons I don't accept any pull requests
> 
> Care to elaborate? Could you document this publicly in e.g. the README?

Sure. Basically I need to maintain full ownership of the code base so that I can manage other licenses (Apple won't accept GPL'd code in their App Store), though I think there are some apps out there that are GPL'd and on the App Store (from what I can tell, they are not supposed to be there). 

Anyway, to maintain my ability to manage licensing fully for Strongbox I just don't want the hassle of managing ownership and if I accept contributions I would need you or the contributor to assign my all rights. I don't really want to go down that road. 

Even though you've only suggested a change to the README and not actual code, I'm kind of paranoid about this, and as a rule I just don't want to accept changes so that I don't have to worry about problems down the line. I'm probably being overly cautious I'm sure.

I've updated the README and will follow up now with the Contribution Guidelines @Ben-Voris mentioned above. 

I hope that makes sense and thanks for your contribution.
-Mark

**Comment by georgesnow** [comment]
I would concur the GPL part. From what I have seen on other Github repos GPL licensing isn't compatible with the App Store. Now i believe though the MIT licensing would be compatible, but I can understand the sentiment of not having to worry about it.

**Comment by marcelstoer** [comment]
I appreciate your feedback Mark, thank you very much.

> I need to maintain full ownership of the code

Hhmm, you don't, it's in the public domain, no? You are the author but not the owner?

I'm no licensing expert but if I correctly understand your explanations then all App Store apps would have to be written by a single developer? That doesn't sound logical. Bitwarden, one of many [open-source iOS apps](https://en.wikipedia.org/wiki/List_of_free_and_open-source_iOS_applications), is GPL and has 19 contributors on GitHub.

What am I missing?

**Comment by georgesnow** [comment]
https://www.fsf.org/news/2010-05-app-store-compliance

the "ownership" of the code is what he has written. he has published but it is not "public domain". 
the contributors to Bitwarden must agree to release their rights of the work they contributed. ie its a pain in the arse. From a developer point of view a small shop it's easier to only have those that "in-house" developers add to the code. Presumably they have already agreed and signed contracts to say the entity to which they work "own" the code.

**Comment by marcelstoer** [comment]
> the contributors to Bitwarden must agree to release their rights of the work they contributed. ie its a pain in the arse.

Ok, wasn't aware of that. Neither their README nor the contributing guidelines mention this. I wonder how they handle that as not even in PRs of first-time contributors you would see any comments to that end.

**Comment by georgesnow** [comment]
well, its not really clear but if you read that article from FSF. Basically there is sticking points with iOS app store, but apparently not the same for the Mac App Store. Of course it is evolving thing. Actually probably should phrased that differently, but you can retain the copyright, but allow the work to be used. My point being is since there a lot of things you have to deal with it. You could understand restricting contributions.  And if read the GPL license. it requires that software code to be acquirable. it doesn't have to be publish. KeePass Touch did this. You can ask them for a copy, but the maintainers don't keep an update git repo available to the public.

**Comment by mmcguill** [comment]
Yeah, no worries at all @marcelstoer. To be honest I’ve been wondering how to manage this, and yours is actually the first PR I’ve had here... So, to try to answer your questions (and I am not a lawyer). I still own the code I’ve written. I offer it for reuse under the AGPL which means others can use it. Any code that is not mine e.g. the libraries I use are used under different licences, all compatible with the App Store. So the code is not public domain, which is a different categorisation than FOSS or the GPL licence in particular, as @georgesnow has pointed out.

Also as @georgesnow has mentioned above, it seems like BitWarden may have elected for the more complicated process involved to maintain a Dual licensing setup compatible with the App Store.

Again all of this is just my best read on the situation, I don’t have the resources to hire an expert or whatever would be required... it was a tough enough process figuring this all out in the first place. The app was originally closed source, due no other reason than I didn’t think anyone would ever really use it apart from myself and a few other friends (originally it was Password Safe format only). I also didn't want to have to figure out all this licensing bureaucracy but I put in quite a few hours to do so and this is my best read of it... Since the app has grown in popularity and due to popular requests I decided to open source it here for anyone to inspect. 

Anyway, hope that makes sense, and it's probably not ideally what you were looking to hear I'm sure.

**Comment by marcelstoer** [comment]
Again, thanks for your insight.

> yours is actually the first PR I’ve had here

It isn't even _my_ PR 😉I found this by accident and your initial reaction triggered a few questions.

The questions here lead me to read https://haacked.com/archive/2006/01/24/TheDevelopersGuideToCopyrightLaw-Part1.aspx/ (and its part 2 & 3) - very enlightening. 

I was particularly interested in finding out more about your 

> I would need you or the contributor to assign my all rights.

From what I learned it seems this can be achieved in a very simple process (just an idea):

- Create a [PR template](https://help.github.com/en/articles/about-issue-and-pull-request-templates) on GitHub at `.github/pull_request_template.md`
- Add whatever you want to plus `[ ] I hereby assign copyright in this code to the project/founder/Mark McGuill, to be licensed under the same terms as the rest of the code.` The brackets will render as a checkbox contributors can tick. Rendered example below.

Screenshot 2019-06-20 at 22 47 42

**Comment by mmcguill** [comment]
Ok, sorry I got you confused with @kant there... 

Thanks for that, it's interesting reading, and definitely something I'll consider, though I'm a little prone to erring on the side of caution with this. Hope that makes sense.

**Pull request closed without merging**
